[package]
name = "workflow-macro-tools"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-macro-tools"
keywords = ["macro","attributes"]
categories = []
exclude = ["/.*", "/test"]
description = """
Macro utility functions used by the Workflow-RS project
"""

[dependencies]
syn = {version="1.0.91",features=["full","fold","extra-traits","parsing","proc-macro"]}
quote = "1.0.8"
proc-macro2 = { version = "1.0.37" }
parse-variants = "0.1"
convert_case = "0.5.0"


